apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  UUID: ${UUID}
  server.json: |
    {
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "port": 80, 
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "${UUID}"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "https://www.wikipedia.org/",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "https://www.wikipedia.org/",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 3, 
                "connIdle": 120
            }
        }
    }
    }